"""
exact_p_supplement.py -- SUPPLEMENTARY. NOT A REGENERATION OF ANY LOCKED OUTPUT.

The confirmatory family's Social Network tests used 10,000 Monte-Carlo permutations,
because 11! = 39,916,800 exceeded the enumeration limit in fast_stats. That limit is
avoidable: the permutation null distribution of Spearman's rho depends only on the two
rank vectors, so permuting whichever vector carries MORE ties enumerates far fewer
DISTINCT arrangements while giving the identical null distribution. For the primary test
the predictor's tie structure reduces 39,916,800 permutations to 9,240 distinct
arrangements, which enumerate exactly.

This file recomputes exact permutation p-values wherever that reduction makes enumeration
feasible, and re-runs BH-FDR on the confirmatory family with them substituted. It is a
precision refinement of p-values already computed, not a new test, not a new hypothesis,
and not a re-analysis. No locked output is overwritten or regenerated by this script.

Hotel Reservation tests were already exact (7! = 5,040) and are unchanged.

Reads : analysis/final/confirmatory_family_kill.csv (test identities and original p)
        analysis/final/service_level_data.csv       (the vectors themselves)
Writes: analysis/final/exact_p_supplement.csv
        analysis/final/exact_p_supplement.md
"""
from __future__ import annotations

import itertools
import math
import os
from collections import Counter

import numpy as np
import pandas as pd
from scipy import stats

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
FDR_Q = 0.05
ARRANGEMENT_LIMIT = 3_000_000   # distinct arrangements we are willing to enumerate

PRIMARY = ("socialnetwork", "ancestor_count", "ancestor_affected_count")


def distinct_arrangements(ranks):
    n = len(ranks)
    total = math.factorial(n)
    for c in Counter(ranks).values():
        total //= math.factorial(c)
    return total


def exact_p(x, y):
    """Exact two-sided permutation p for Spearman's rho, or (nan, reason) if infeasible.

    Permutes whichever rank vector has the fewer distinct arrangements. Permuting x against
    fixed y and permuting y against fixed x generate the same null distribution of rho, so
    this is a computational choice with no statistical content.
    """
    rx, ry = stats.rankdata(x), stats.rankdata(y)
    rxc, ryc = rx - rx.mean(), ry - ry.mean()
    den = math.sqrt(float((rxc * rxc).sum()) * float((ryc * ryc).sum()))
    if den == 0.0:
        return float("nan"), float("nan"), 0, "undefined (a variable is constant)"
    obs = float((rxc * ryc).sum() / den)

    nx, ny = distinct_arrangements(rx), distinct_arrangements(ry)
    if min(nx, ny) > ARRANGEMENT_LIMIT:
        return obs, float("nan"), min(nx, ny), (
            "not enumerated: %s distinct arrangements exceed the %s limit"
            % (format(min(nx, ny), ","), format(ARRANGEMENT_LIMIT, ",")))

    if nx <= ny:
        moving, fixed, n_dis = rxc, ryc, nx
    else:
        moving, fixed, n_dis = ryc, rxc, ny

    uniq = sorted(set(itertools.permutations(moving)))
    assert len(uniq) == n_dis, (len(uniq), n_dis)
    rhos = np.asarray(uniq, dtype=float) @ fixed / den
    hits = int((np.abs(rhos) >= abs(obs) - 1e-12).sum())
    return obs, hits / n_dis, n_dis, (
        "exact enumeration of %s distinct arrangements (%s permutations)"
        % (format(n_dis, ","), format(math.factorial(len(x)), ",")))


def bh(pvals):
    """Benjamini-Hochberg adjusted p-values. NaN entries are excluded from the family."""
    p = np.asarray(pvals, dtype=float)
    ok = ~np.isnan(p)
    out = np.full(p.shape, np.nan)
    sub = p[ok]
    m = sub.size
    order = np.argsort(sub, kind="mergesort")
    adj = np.empty(m)
    running = 1.0
    for i in range(m - 1, -1, -1):
        running = min(running, sub[order[i]] * m / (i + 1))
        adj[order[i]] = running
    out[ok] = adj
    return out, int(ok.sum())


def main():
    conf = pd.read_csv(os.path.join(HERE, "confirmatory_family_kill.csv"))
    svc = pd.read_csv(os.path.join(HERE, "service_level_data.csv"))

    rows = []
    for _, t in conf.iterrows():
        d = svc[(svc.app == t.architecture) & (svc.fault_type == "kill")
                & (svc.in_analysis_set)].sort_values("service")
        x = d[t.predictor].to_numpy(dtype=float)
        y = d[t.outcome].to_numpy(dtype=float)
        rho, pe, n_dis, method = exact_p(x, y)
        rows.append({
            "status": "SUPPLEMENTARY precision refinement of p-values; "
                      "not a re-analysis and not a locked output",
            "family": "confirmatory (kill)",
            "architecture": t.architecture,
            "architecture_label": t.architecture_label,
            "predictor": t.predictor,
            "outcome": t.outcome,
            "is_primary_test": bool((t.architecture, t.predictor, t.outcome) == PRIMARY),
            "n_services": int(t.n_services),
            "spearman_rho_locked": t.spearman_rho,
            "spearman_rho_recomputed": None if math.isnan(rho) else round(rho, 6),
            "p_locked": t.p_permutation,
            "p_method_locked": t.p_method,
            "p_exact_supplementary": None if (pe != pe) else round(pe, 8),
            "exact_distinct_arrangements": n_dis,
            "exact_method": method,
            "p_bh_locked": t.p_bh_adjusted,
            "significant_after_fdr_locked": t.significant_after_fdr,
        })

    out = pd.DataFrame(rows)

    # (1) Substitute the PRIMARY test's exact p only -- what was asked for.
    p_primary_only = out["p_locked"].to_numpy(dtype=float).copy()
    idx = out.index[out.is_primary_test]
    assert len(idx) == 1, "expected exactly one primary test"
    i = int(idx[0])
    p_primary_only[i] = float(out.loc[i, "p_exact_supplementary"])
    bh_primary_only, m1 = bh(p_primary_only)
    out["p_bh_with_exact_primary_only"] = np.round(bh_primary_only, 6)

    # (2) Substitute every exact p that could be enumerated.
    p_all = out["p_locked"].to_numpy(dtype=float).copy()
    have = out["p_exact_supplementary"].notna().to_numpy()
    p_all[have] = out.loc[have, "p_exact_supplementary"].to_numpy(dtype=float)
    bh_all, m2 = bh(p_all)
    out["p_bh_with_all_available_exact"] = np.round(bh_all, 6)

    out["significant_after_fdr_with_exact"] = out["p_bh_with_all_available_exact"] < FDR_Q
    out["fdr_q"] = FDR_Q
    out["family_size_tested"] = m2

    out.to_csv(os.path.join(HERE, "exact_p_supplement.csv"), index=False)

    r = out.loc[i]
    n_ref = int(have.sum())
    n_chg = int((np.abs(np.nan_to_num(p_all) - np.nan_to_num(
        out["p_locked"].to_numpy(dtype=float))) > 1e-12).sum())
    sig_locked = int(out["significant_after_fdr_locked"].sum())
    sig_exact = int(out["significant_after_fdr_with_exact"].sum())

    tick = chr(96)
    L = []
    A = L.append
    A("# Exact permutation p-values: supplementary refinement")
    A("")
    A("**SUPPLEMENTARY. Not a re-analysis, not a locked output, not a new test.** "
      "Produced by " + tick + "analysis/final/exact_p_supplement.py" + tick + ". "
      "Full table: " + tick + "exact_p_supplement.csv" + tick + ".")
    A("")
    A("The Social Network tests in the locked confirmatory family used 10,000 Monte-Carlo "
      "permutations because 11! = 39,916,800 exceeded the enumeration limit. Permuting the "
      "rank vector with more ties enumerates the identical null distribution from far fewer "
      "distinct arrangements, so those p-values can be made exact after the fact. Hotel "
      "Reservation tests were already exact (7! = 5,040) and are unchanged.")
    A("")
    A("## Primary test")
    A("")
    A("| quantity | value |")
    A("|---|---|")
    A("| test | Social Network, ancestor_count vs ancestor_affected_count, kill faults |")
    A("| Spearman rho | %s (unchanged; recomputed %s) |"
      % (r["spearman_rho_locked"], r["spearman_rho_recomputed"]))
    A("| raw p, locked (10,000 Monte-Carlo) | **%s** |" % r["p_locked"])
    A("| raw p, exact enumeration | **%.8f** = 64/9,240 |" % r["p_exact_supplementary"])
    A("| enumeration | %s |" % r["exact_method"])
    A("| BH-adjusted p, locked | **%s** |" % r["p_bh_locked"])
    A("| BH-adjusted p, exact primary substituted | **%s** |"
      % r["p_bh_with_exact_primary_only"])
    A("| BH-adjusted p, all available exact substituted | **%s** |"
      % r["p_bh_with_all_available_exact"])
    A("| significant at q = %.2f | **%s -> %s** |"
      % (FDR_Q, r["significant_after_fdr_locked"],
         r["significant_after_fdr_with_exact"]))
    A("")
    A("## Family-level effect")
    A("")
    A("| quantity | value |")
    A("|---|---|")
    A("| tests in family | %d |" % len(out))
    A("| tests with a defined p | %d |" % m2)
    A("| tests refined to an exact p | %d |" % n_ref)
    A("| tests whose raw p changed at all | %d |" % n_chg)
    A("| significant after BH-FDR, locked | **%d** |" % sig_locked)
    A("| significant after BH-FDR, with exact p | **%d** |" % sig_exact)
    A("")
    if sig_locked == sig_exact == 0:
        A("**The BH-adjusted verdict is unchanged: 0 of 44 confirmatory tests are "
          "significant at q = 0.05, before and after this refinement.** The primary test's "
          "adjusted p moves by a fraction of a percent and remains roughly an order of "
          "magnitude above the threshold.")
    else:
        A("**THE VERDICT CHANGED: %d significant before, %d after.** Reported as found."
          % (sig_locked, sig_exact))
    A("")
    A("## Correction to an earlier figure")
    A("")
    A("An earlier supplementary note (" + tick + "blind_recompute.md" + tick + ") reported "
      "**0.006883** for this test from 2,000,000 Monte-Carlo pairings and described it as "
      "high-resolution. It is a Monte-Carlo estimate, not an exact value. The exact value "
      "is **0.00692641** (64 of 9,240 arrangements). The difference, 4.3e-05, is within "
      "Monte-Carlo error for 2,000,000 resamples and changes nothing, but the exact value "
      "is the one that should be cited.")

    open(os.path.join(HERE, "exact_p_supplement.md"), "w", encoding="utf-8").write(
        "\n".join(L) + "\n")

    print("primary: locked p=%s  exact p=%.8f  BH locked=%s  BH exact=%s  sig %s -> %s"
          % (r["p_locked"], r["p_exact_supplementary"], r["p_bh_locked"],
             r["p_bh_with_all_available_exact"],
             r["significant_after_fdr_locked"], r["significant_after_fdr_with_exact"]))
    print("family: %d tests, %d refined to exact, significant %d -> %d"
          % (len(out), n_ref, sig_locked, sig_exact))
    print("wrote exact_p_supplement.csv and exact_p_supplement.md")


if __name__ == "__main__":
    main()
