
"""
_locustfile_hotel.py — Locust load task definitions for Hotel Reservation.
Auto-generated by generate_hotel_load.py. Do not edit manually.
"""

import random
from locust import HttpUser, task, between

HOTEL_LOCATIONS = [
    (37.7867, -122.4112),
    (37.7794, -122.4062),
    (38.0235, -122.095),
    (37.6879, -122.4702),
    (37.3382, -121.8863),
]

DATE_PAIRS = [
    ("2015-04-09", "2015-04-10"),
    ("2015-04-10", "2015-04-11"),
    ("2015-04-11", "2015-04-12"),
]

USERS = [f"Cornell_{i}" for i in range(1, 51)]
HOTELS = list(range(1, 21))


def _credentials():
    """Return a (username, password) pair in DeathStarBench's seeded format.

    DSB seeds hotelReservation users as username "Cornell_<i>" with password equal to
    the digit <i> repeated 10 times. BOTH fields are mandatory: frontend/server.go
    returns HTTP 400 "Please specify username and password" and returns BEFORE issuing
    the CheckUser RPC if either is missing. Omitting the password is why the `user`
    service never appeared in any trace, and therefore never appeared in the dependency
    graph. See _audit/TELEMETRY_DIAGNOSIS.md section 3.
    """
    i = random.randint(1, 50)
    return f"Cornell_{i}", str(i % 10) * 10


class HotelUser(HttpUser):
    wait_time = between(0.5, 1.5)

    @task(6)
    def hotel_search(self):
        lat, lon = random.choice(HOTEL_LOCATIONS)
        in_date, out_date = random.choice(DATE_PAIRS)
        with self.client.get(
            "/hotels",
            params={"inDate": in_date, "outDate": out_date,
                    "lat": str(lat), "lon": str(lon)},
            catch_response=True,
            name="/hotels [search]",
        ) as r:
            if r.status_code >= 400:
                r.failure(f"HTTP {r.status_code}: {r.text[:120]}")

    @task(2)
    def make_reservation(self):
        # reservationHandler reads r.URL.Query() -- QUERY PARAMS, not a JSON body -- and
        # requires inDate, outDate, hotelId, customerName, username, password. The room
        # count field is `number`, not `roomNumber`. Sending a JSON body produced HTTP
        # 400 on 100% of requests (55/55 in hotel_load_stats_failures.csv).
        in_date, out_date = random.choice(DATE_PAIRS)
        lat, lon = random.choice(HOTEL_LOCATIONS)
        username, password = _credentials()
        with self.client.post(
            "/reservation",
            params={
                "inDate": in_date,
                "outDate": out_date,
                "lat": str(lat),
                "lon": str(lon),
                "hotelId": str(random.choice(HOTELS)),
                "customerName": username,
                "username": username,
                "password": password,
                "number": str(random.randint(1, 5)),
            },
            catch_response=True,
            name="/reservation [book]",
        ) as r:
            if r.status_code >= 400:
                r.failure(f"HTTP {r.status_code}: {r.text[:120]}")

    @task(2)
    def get_user(self):
        # userHandler requires BOTH username and password, else HTTP 400 before the
        # CheckUser RPC. Without the password no frontend->user span is ever emitted.
        username, password = _credentials()
        with self.client.get(
            "/user",
            params={"username": username, "password": password},
            catch_response=True,
            name="/user [lookup]",
        ) as r:
            if r.status_code >= 400:
                r.failure(f"HTTP {r.status_code}: {r.text[:120]}")

    @task(1)
    def get_recommendations(self):
        lat, lon = random.choice(HOTEL_LOCATIONS)
        with self.client.get(
            "/recommendations",
            params={"require": random.choice(["dis", "rate", "price"]),
                    "lat": str(lat), "lon": str(lon)},
            catch_response=True,
            name="/recommendations",
        ) as r:
            if r.status_code >= 400:
                r.failure(f"HTTP {r.status_code}: {r.text[:120]}")
