"""
emit_macros.py -- turn paper/numbers.csv into paper/numbers.tex and paper/numbers.json.

Reads numbers.csv and nothing else, so the CSV stays the single source of truth. Every
citable number becomes a LaTeX macro and a JSON key, and the manuscript references those
instead of typing a digit.

LaTeX macro names may contain only letters, so claim_ids are CamelCased and digits are
spelled out: `primary_p95_ms` -> \\NumPrimaryPNineFiveMs. Collisions are a hard error, not
a silent overwrite.

Run: python paper/build_numbers.py && python paper/emit_macros.py
"""
from __future__ import annotations

import json
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
DIGITS = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
          "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}


def macro_name(claim_id: str) -> str:
    out = []
    for part in claim_id.split("_"):
        chunk = "".join(DIGITS[c] if c.isdigit() else c for c in part)
        out.append(chunk[:1].upper() + chunk[1:] if chunk else "")
    name = "Num" + "".join(out)
    return "".join(c for c in name if c.isalpha())


def tex_escape(v: str) -> str:
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                 ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
                 ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")):
        v = v.replace(a, b)
    return v


def main() -> None:
    df = pd.read_csv(os.path.join(HERE, "numbers.csv"), dtype=str).fillna("")
    commit = df["commit"].iloc[0] if len(df) else "UNKNOWN"

    names = {}
    for cid in df.claim_id:
        m = macro_name(cid)
        if m in names:
            raise SystemExit("macro collision: %s and %s both -> %s" % (names[m], cid, m))
        names[m] = cid

    lines = [
        "%% paper/numbers.tex -- AUTO-GENERATED from paper/numbers.csv. DO NOT EDIT.",
        "%% Regenerate: python paper/build_numbers.py && python paper/emit_macros.py",
        "%% Generated at repository commit %s. %d macros." % (commit, len(df)),
        "",
    ]
    for _, r in df.iterrows():
        lines.append("%% %s (%s)" % (r.description, r.source_file))
        lines.append("\\newcommand{\\%s}{%s}" % (macro_name(r.claim_id), tex_escape(r.value)))
    open(os.path.join(HERE, "numbers.tex"), "w", encoding="utf-8").write("\n".join(lines) + "\n")

    payload = {
        "_generated_from": "paper/numbers.csv",
        "_generated_by": "paper/emit_macros.py",
        "_commit": commit,
        "_count": len(df),
        "_note": ("Values are display-formatted strings. value_raw in numbers.csv holds "
                  "full precision. Do not edit this file; regenerate it."),
        "values": {r.claim_id: r.value for _, r in df.iterrows()},
        "raw": {r.claim_id: r.value_raw for _, r in df.iterrows()},
        "descriptions": {r.claim_id: r.description for _, r in df.iterrows()},
        "sources": {r.claim_id: {"file": r.source_file, "script": r.source_script}
                    for _, r in df.iterrows()},
    }
    with open(os.path.join(HERE, "numbers.json"), "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=1)
        fh.write("\n")

    print("wrote paper/numbers.tex and paper/numbers.json (%d entries, commit %s)"
          % (len(df), commit))
    for cid in ("primary_rho", "primary_p_exact", "campaign_runs_total"):
        if cid in set(df.claim_id):
            print("  e.g. \\%s -> %s" % (macro_name(cid),
                                         df[df.claim_id == cid].value.iloc[0]))


if __name__ == "__main__":
    main()
